version: '2.3'

services:
  
  # Building Tfrecord
  cross-sell-prediction:
    image: doctorai/cross-sell-prediction
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    tty: true  
    ports: 
      - "8080:8080"
    command: python transfer_learning_with_keras/build_tf_record.py   
